package com.coherence.demo.common.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.coherence.demo.common.entity.Employee;
import com.coherence.demo.common.entity.EmployeeExample;

public interface EmployeeService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	Employee selectByPrimaryKey(Short id);
	
	Employee selectByPrimaryKeyUnion(Map<String, List<Short>> searchMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table EMPLOYEE
	 *
	 * @mbg.generated Thu Mar 15 17:24:44 CST 2018
	 */
	int updateByPrimaryKey(Employee record);
}