package com.coherence.demo.common.entity;

import java.math.BigDecimal;

public class Employee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.ID
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private BigDecimal id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.FIRSTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.LASTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.EMAIL
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.PHONE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.BIRTHDATE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String birthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.TITLE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEE.DEPARTMENT
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	private String department;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.ID
	 * @return  the value of EMPLOYEE.ID
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.ID
	 * @param id  the value for EMPLOYEE.ID
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.FIRSTNAME
	 * @return  the value of EMPLOYEE.FIRSTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.FIRSTNAME
	 * @param firstname  the value for EMPLOYEE.FIRSTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.LASTNAME
	 * @return  the value of EMPLOYEE.LASTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.LASTNAME
	 * @param lastname  the value for EMPLOYEE.LASTNAME
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.EMAIL
	 * @return  the value of EMPLOYEE.EMAIL
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.EMAIL
	 * @param email  the value for EMPLOYEE.EMAIL
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.PHONE
	 * @return  the value of EMPLOYEE.PHONE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.PHONE
	 * @param phone  the value for EMPLOYEE.PHONE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.BIRTHDATE
	 * @return  the value of EMPLOYEE.BIRTHDATE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.BIRTHDATE
	 * @param birthdate  the value for EMPLOYEE.BIRTHDATE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.TITLE
	 * @return  the value of EMPLOYEE.TITLE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.TITLE
	 * @param title  the value for EMPLOYEE.TITLE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEE.DEPARTMENT
	 * @return  the value of EMPLOYEE.DEPARTMENT
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEE.DEPARTMENT
	 * @param department  the value for EMPLOYEE.DEPARTMENT
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	public void setDepartment(String department) {
		this.department = department;
	}
}