package com.coherence.demo.common.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.coherence.demo.common.entity.Employee;
import com.coherence.demo.common.entity.EmployeeExample;
import java.math.BigDecimal;

public interface EmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	long countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int deleteByPrimaryKey(BigDecimal id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	Employee selectByPrimaryKey(BigDecimal id);
	
	Employee selectByPrimaryKeyUseUnion(Map<String, List<BigDecimal>> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEE
	 * @mbg.generated  Fri Aug 03 16:12:36 CST 2018
	 */
	int updateByPrimaryKey(Employee record);

	Employee selectByPrimaryKeyUnion(Map<String, List<Short>> searchMap);
}